myclothstore/myclothstore/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', views.login_user, name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/cart_remove/', views.cart_remove, name='cart_remove'),
    path('cart/item_increase/<int:id>/', views.item_increase, name='item_increase'),
    path('cart/item_decrease/<int:id>/', views.item_decrease, name='item_decrease'),
    path('cart/cart_detail/', views.cart_detail, name='cart_detail'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('contact/', views.contact_us, name='contactus'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/', views.order, name='yourorder'),
    path('payment/', views.paymentdone, name="paymentdone"),
    path('product/', views.product, name='product'),
    path('product/<str:id>', views.productdetail, name='productdetail'),
    path('search/', views.search, name='search'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myclothstore/home/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
import datetime
from django.core.exceptions import ValidationError

# Create your models here.
class Basemodel(models.Model):
    uid = models.UUIDField(primary_key=True,editable=False,default=uuid.uuid4)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    Availability = (('In Stock','In stock'),('Out Of Stoke','Out Of Stoke'))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE,default='',related_name='subcategory')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='product/img')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    availability = models.CharField(choices=Availability, null=True, max_length=100)
    description = models.TextField(null=True)
    date = models.DateField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.name



class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self) -> str:
        return self.email
    
class Order(models.Model):
    image = models.ImageField(upload_to='product/order')
    product = models.CharField(max_length=100, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=5)
    total = models.CharField(max_length=10, default='')
    address = models.TextField()
    mobile = models.CharField(max_length=18)
    pincode = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self) -> str:
        return self.user.username

myclothstore/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UsercreateForm(UserCreationForm):

    email = forms.EmailField(required=True, label='Email', error_messages={'exists':'This is Already Exist'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')
    
    def __init__(self, *args,**kwargs):
        super(UsercreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'


    def save(self, commit=True):
        user =super(UsercreateForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
    def clean_email(self):
        if User.objects.filter(email = self.cleaned_data['email']).exists():
            raise forms.ValidationError('Email Already Register')
        return self.cleaned_data['email']

myclothstore/home/views.py
from django.shortcuts import render, redirect, HttpResponse
from home.models import Category,SubCategory,Product,Contact_us, Order,Brand
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
# from home.models import UsercreateForm
from .forms import UsercreateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from cart.cart import Cart

# Create your views here.
def home(request):
    category = Category.objects.all()
    categoryId = request.GET.get('category')
    brands = Brand.objects.all()
    brandId =  request.GET.get('brand')
    if categoryId:
        product = Product.objects.filter(subcategory=categoryId).order_by('-id')
    elif brandId:
        product = Product.objects.filter(brand=brandId).order_by('-id')
    else:
        product = Product.objects.all()

    paginator = Paginator(product,6 )
    page_no = request.GET.get('page')
    pageshow = paginator.get_page(page_no)
    context = {'category':category,'product':pageshow,'brands':brands}
    return render(request, 'home/index.html', context)


def signup(request):    
    if request.method == 'POST':
        form = UsercreateForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            messages.success(request, "Registration successful." )
            return redirect('login')        
        messages.error(request, 'Invalid Information')

    else:

        form = UsercreateForm()
    context = {
        'form':form,
    }
    return render(request, 'registration/signup.html',context)

    
def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        # form = UsercreateForm()
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}.")
                return redirect('home')
        else:
            messages.error(request,"Invalid username or password.")
    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html',{'form':form} )    
def product(request):
    brand = Brand.objects.all()
    brandId = request.GET.get('brand')
    category = Category.objects.all()
    categoryid = request.GET.get('category')
    if brandId:
        products = Product.objects.filter(brand=brandId).order_by('-id')
    elif categoryid:
        products = Product.objects.filter(subcategory=categoryid).order_by('-id')
    else:
        products = Product.objects.all()
    
    paginator = Paginator(products,3 )
    page_no = request.GET.get('page')
    pageshow = paginator.get_page(page_no)
    
    context = {'product':pageshow,'brand':brand,'category':category,'products':products}

    return render(request, 'home/product.html',context)

def productdetail(request, id):
    product = Product.objects.filter(id=id).first()
    context = {'product':product}
    return render(request, 'home/productdetail.html', context)

def search(request):
    query = request.GET['query']
    product = Product.objects.filter(name__icontains = query)
    context = {'product':product}
    return render(request, 'home/search.html', context)

@login_required(login_url='/accounts/login/')
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id = id)
    cart.add(product=product)
    return redirect('home')

@login_required(login_url='/accounts/login/')
def cart_remove(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart_detail')

@login_required(login_url='/accounts/login/')
def item_increase(request, id):
    cart = Cart(request)
    product = Product.objects.get(id = id)
    cart.add(product=product)
    return redirect('cart_detail')

@login_required(login_url='/accounts/login/')
def item_decrease(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect('cart_detail')


@login_required(login_url='/accounts/login/')
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect('cart_detail')

@login_required(login_url='/accounts/login/')
def cart_detail(request):
    return render(request,'cart/cart_detail.html')

def contact_us(request):
    if request.method == "POST":
        contact = Contact_us(
            name = request.POST.get('name'),
            email = request.POST.get('email'),
            subject = request.POST.get('subject'),
            message = request.POST.get('message')
        )
        contact.save()
    return render(request, 'home/contact.html')

def checkout(request):
    if request.method == 'POST':
        mobile = request.POST.get('mobile')
        address = request.POST.get('address')
        pincode = request.POST.get('pincode')
        cart = request.session.get('cart')
        uid = request.session.get('_auth_user_id')
        user = User.objects.get(pk=uid)
        # print(mobile, address, pincode, cart, user)

        for i in cart:
            # print(i)
            a = int(cart[i]['price'])
            b = cart[i]['quantity']
            total = (a * b)
            order= Order(
                user = user,
                product = cart[i]['name'],
                price = cart[i]['price'],
                quantity = cart[i]['quantity'],
                image = cart[i]['image'],
                address = address,
                mobile = mobile,
                total = total,
                pincode = pincode

            )
            order.save()
            request.session['cart'] = {}
        return redirect('yourorder')
    return HttpResponse('this is checkout ')


@login_required(login_url='/accounts/login/')
def order(request):
    uid = request.session.get('_auth_user_id')
    user = User.objects.get(pk=uid)
    order = Order.objects.filter(user=user)
    context = {'order':order}
    return render(request, 'home/order.html', context)

def paymentdone(request):
    user = request.user
    uid = request.session.get('_auth_user_id')
    user = User.objects.get(pk=uid)
    cart = Order.objects.filter(user=user)
    for i in cart:
        Order(user=user, product=i.product,quantity=i.quantity).save()
    return redirect('yourorder')

myclothstore/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-CLOTHSTORE</title>
    <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="./static/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="./static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="./static/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +91 7878784545</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> www.mycloths.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="./static/images/home/logo.png" alt="" /></a>
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>
							
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canadian Dollar</a></li>
									<li><a href="#">Pound</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="{% url 'yourorder'%}"><i class="fa fa-star"></i> Your Order</a></li>
								<!-- <li><a href="{% url 'checkout'%}"><i class="fa fa-crosshairs"></i> Checkout</a></li> -->
								<li><a href="{% url 'cart_detail'%}"><i class="fa fa-shopping-cart"></i> Cart<span class="badge badge-secondary">{{request.session.cart|length}}</span</a></li>
							{% if user.is_authenticated %}
								<li><a href="{% url 'logout'%}">{{request.user.username|capfirst}}&nbsp;<i class="fa fa-lock"></i> Logout</a></li>
							{% else %}		
								<li><a href="{% url 'login' %}"><i class="fa fa-lock"></i> Login</a></li>
							{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'home' %}" class="active">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'product' %}">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li> 
										<li><a href="checkout.html">Checkout</a></li> 
										<li><a href="{% url 'cart_detail'%}">Cart<span class="badge badge-secondary">New</span</a></li> 
										<li><a href="login.html">Login</a></li> 
                                    </ul>
                                </li> 
								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li> 
								<li><a href="404.html">404</a></li>
								<li><a href="{% url 'contactus'%}">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<form action="/search/" method="get">
						<div class="search_box pull-right">
							<input  name="query" type="text" placeholder="Search"/>
						</div>
						</form>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

    {% block main %}

    {% endblock %}
	{% block paymentgateway %}
	  
	{% endblock paymentgateway %}

    <footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-clothstore</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe1.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe2.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="images/home/map.png" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="{% url 'contactus'%}">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About CLOTHSTORE</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About CLOTHSTORE</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-CLOTHSTORE Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

  
    <script src="{% static 'js/jquery.js' %}" ></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/myscript.js' %}"></script>
</body>
</html>

myclothstore/home/templates/home/product.html
{% extends 'home/base.html' %}
{% block main %}
<section id="advertisement">
    <div class="container">
        <img src="images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                        {% for i in category %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordian" href="#{{i.id}}">
                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                        {{i.name}}
                                    </a>
                                </h4>
                            </div>
                            <div id="{{i.id}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                    {% for cat in i.subcategory_set.all %}
                                        <li><a href="{{cat.id}}"><a href="/product/?category={{cat.id}} & brand={{cat.id}}">{{cat.name}}</a></a></li>
                                    {% endfor %}    
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div><!--/category-productsr-->
                
                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                        {% for i in brand %}

                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="/product/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
                            </ul>
                        {% endfor %}

                        </div>
                    </div><!--/brands_products-->
                    
                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                             <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                             <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->
                    
                    <div class="shipping text-center"><!--shipping-->
                        <img src="images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->
                    
                </div>
            </div>
            
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    {% for i in product %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <img src="{{i.image.url}}"  height="200px" alt="" />
                                    <h2>₹ {{i.price}}</h2>
                                    <p>{{i.name}}</p>
                                    <a href="{% url 'cart_add' i.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                                <div class="product-overlay">
                                    <div class="overlay-content">
                                        <h2>₹ {{i.price}}</h2>
                                        <p>{{i.name}}</p>
                                        <a href="{% url 'cart_add' i.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </div>
                                </div>
                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">
                                    <li><a href="{{ i.id }}"><i class="fa fa-plus-square"></i>View Product</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor  %}
                    
                    <ul class="pagination">
                        {% if product.has_previous %}
                        <li><a href="/product/?page={{product.previous_page_number}}">&laquo;</a></li>
                        {% endif %}
                        
                        {% for i in product.paginator.page_range %}
                            {% if product.number == i %}
                                <li class="active"> <a class="current" href="#">{{i}}</a></li>
                            {% else %}
                                <li > <a href="?page={{i}}">{{i}}</a></li>
                            {% endif%}    
                        {% endfor %}
                        
                        {% if product.has_next %}
                        <li><a href="/product/?page={{product.next_page_number}}">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>
{% endblock %}

myclothstore/home/templates/home/search.html
{% extends 'home/base.html' %}
{% block main %}
<div class="container">
<div class="features_items"><!--features_items-->
    <h2 class="title text-center">Search Result</h2>
    {% if product|length < 1 %}
    <div class="content-404">
        <img src="images/404/404.png" class="img-responsive" alt="" />
        <h1><b>OPPS!</b> We Couldn’t Find this Page</h1>
        <p>Uh... There is no related data found.</p>
        <h2><a href="{% url 'home' %}">Bring me back Home</a></h2><br>
    </div>
    {% endif %}
    {% for i  in product %}
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="{{i.image.url}}" height="200px;"  alt="" />
                        <h2>₹{{i.price}}</h2>
                        <p>{{i.name}}</p>
                        
                        <a href="{% url 'cart_add' i.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>₹{{i.price}}</h2>
                            <p>{{i.name}}</p>
                            <a href="{% url 'cart_add' i.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                    </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>View Product</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}

</div><!--features_items-->
</div>
{% endblock %}